### ISSUE TITLE
harvest.py --annotation option usage is obscure

### ISSUE THREAD

**Issue by NicolasMICAUX** [kermitt2/article-dataset-builder#2]
Hi,
I cannot figure out what infos `--annotation` will give me (I want all references with their coordinates in the PDF file), and where this infos are stored once downloaded (btw script generates a .json file but no .xml or .tei).
Thx for your help

My current code is simple test: ```python3 harvest.py --dois "/home/.../doi.txt" --annotation```

**Comment by kermitt2** [comment]
Hello @NicolasMICAUX !

I reviewed the latest changes and I just pushed some additional checks on the configuration. I also added as default parameter call the addition of coordinates in the TEI file. 

> where this infos are stored once downloaded (btw script generates a .json file but no .xml or .tei).

This is documented, with generated file types and metadata index infos, here:
https://github.com/kermitt2/article-dataset-builder#generated-files

The simple *.json file gives the metadata information. The `*-ref-annotations.json` file gives what is necessary to annotate in a "visual" manner the reference markers and reference in a PDF. 

The generated TEI file now contains also all the coordinates (reference markers and references with coordinates and fully parsed structures).

> python3 harvest.py --dois "/home/.../doi.txt" --annotation

This works fine for me, be sure to complete the `config.json`with the external service information. 

```
(env) lopez@work:~/article-dataset-builder$ ll  data/41/26/26/58/41262658-9da3-488f-b064-4a1c9330d237/
total 180K
drwxrwxr-x 2 lopez lopez 4.0K Aug 30 12:10 ./
drwxrwxr-x 3 lopez lopez 4.0K Aug 30 12:10 ../
-rw-rw-r-- 1 lopez lopez  59K Aug 30 12:10 41262658-9da3-488f-b064-4a1c9330d237.grobid.tei.xml
-rw-rw-r-- 1 lopez lopez 2.2K Aug 30 12:10 41262658-9da3-488f-b064-4a1c9330d237.json
-rw-rw-r-- 1 lopez lopez  89K Aug 30 12:10 41262658-9da3-488f-b064-4a1c9330d237.pdf
-rw-rw-r-- 1 lopez lopez  14K Aug 30 12:10 41262658-9da3-488f-b064-4a1c9330d237-ref-annotations.json
```

**Comment by kermitt2** [comment]
Just an additional comment, if you don't get the expected resources under the data path given in the `config.json` file, the logs available in `harvester.log` should point to the possible errors (service not available or similar).

**Comment by NicolasMICAUX** [comment]
Hi,
Thanks for the answer
It's been long since I last worked on this, but i'll check your solution
